name: Build and publish classification service to docker hub

on:
  push:
    tags: [ 'release/classification' ]

env:
  REGISTRY: docker.io
  API_IMAGE_NAME: trolllemon/classification-api
  BACKEND_IMAGE_NAME: trolllemon/classification-backend
   
jobs:
  build-and-publish-api-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.API_IMAGE_NAME }}
      - name: get tag from commit 
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "version=${TAG}_edge" >> $GITHUB_ENV
      - name: Build and push Docker image for API image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./services/Ml/Classification 
          file: ./services/Ml/Classification/Dockerfile.fastapi
          tags: ${{ env.API_IMAGE_NAME }}:${{ env.version_api }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true 

  build-and-publish-backend-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
      - name: get tag from commit 
          TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $TAG"
          echo "version=${TAG}_edge" >> $GITHUB_ENV
      - name: Build and push Docker image for API image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: ./services/Ml/Classification 
          file: ./services/Ml/Classification/Dockerfile.backend
          tags:   ${{ env.BACKEND_IMAGE_NAME }}:${{ env.version_backend }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
